openapi: 3.0.1
info:
  title: DuckQuery API
  description: API for querying data from a DuckDB database
  version: 1.0.0
paths:
  /duckQuery:
    post:
      operationId: post_duckQuery_execute
      description: Execute a query on a DuckDB database
      requestBody:
        description: DuckDB query details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                procedureId:
                  type: string
                  description: Unique identifier for the procedure
                  nullable: true
                query:
                  type: string
                  description: SQL Query
      responses:
        '200':
          description: Successful response with query results
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultSet:
                    type: array
                    description: Results returned by the query
                    items:
                      type: object
                      description: A single row of query results
        default:
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
